### ISSUE TITLE
metamask not uploading

### ISSUE THREAD

**Issue by nokapzxackx** [KSCHdsc/BlackCap-Grabber#10]
its ziping the metamask_google.zip but never uploads it to my webhook. fix it lol

**Comment by KSCHdsc** [comment]
thx for issue i will fix that now!

**Comment by KSCHdsc** [comment]
you don't receive the "sensitive files webhook" ??

**Comment by nokapzxackx** [comment]
This is what i receive sometimes they're 0kb sometimes they're not. 
[https://ibb.co/mypctM5](url)
[https://ibb.co/VpKBtz1](url)

**Comment by KSCHdsc** [comment]
okay i fix that now

**Comment by KSCHdsc** [comment]
do you have your correct login in "metamask_google.zip"

**Comment by KSCHdsc** [comment]
on victim computer

**Comment by nokapzxackx** [comment]
Wym correct login? im testing it on my host. I have my metamask working fine
It's zipping the file but not uploading
metamask_google.zip

**Comment by KSCHdsc** [comment]
okay

**Comment by KSCHdsc** [comment]
i push the code in 2sec :)
 https://media.discordapp.net/attachments/1032256615962906655/1038930121580621894/image.png

**Comment by nokapzxackx** [comment]
Still not uploading metamask!

**Comment by nokapzxackx** [comment]
![image](https://user-images.githubusercontent.com/70822960/200198556-9e2e8bbb-e1ce-42c8-b234-ab609c3b0d42.png)

**Comment by nokapzxackx** [comment]
![image](https://user-images.githubusercontent.com/70822960/200198693-29681e54-fb36-43af-a390-2d4d0c5b3e24.png)

**Comment by KSCHdsc** [comment]
okay i suppose it's an path error can you add me on discord to debug it?
KSCH reposty#0777

**Comment by nokapzxackx** [comment]
Added you d0gger
