### ISSUE TITLE
Incorrect Roblox cookie

### ISSUE THREAD

**Issue by deceased1** [KSCHdsc/BlackCap-Grabber#104]
I ran the grabber on my device and it gave me an incorrect cookie

**Comment by deceased1** [comment]
(for roblox)

**Comment by KSCHdsc** [comment]
Probably it’s your old cookie

**Comment by deceased1** [comment]
> Probably it’s your old cookie

it happens with every grabber i try

**Comment by deceased1** [comment]
and it wasnt my old one
