### ISSUE TITLE
Is there any DualHook included in the BlackCap Grabber software?

### ISSUE THREAD

**Issue by maestra1336** [KSCHdsc/BlackCap-Grabber#105]
Is there any DualHook included in the BlackCap Grabber software?

**Comment by deceased1** [comment]
like if there was he was just gonna tell you

**Comment by KSCHdsc** [comment]
Bruh no

**Comment by maestra1336** [comment]
https://github.com/Inplex-sys/BlackCap-Grabber-NoDualHook ?
