### ISSUE TITLE
now the exe isnt building

### ISSUE THREAD

**Issue by nokapzxackx** [KSCHdsc/BlackCap-Grabber#11]
its building it as obfuscated.exe then i run it nothing happens. i think u messed up again

**Comment by nokapzxackx** [comment]
![image](https://user-images.githubusercontent.com/70822960/200198148-f6738d8e-5b08-4ab6-842d-943f8b3f8b3b.png)

**Comment by nokapzxackx** [comment]
This error shows when running the exe

**Comment by KSCHdsc** [comment]
with same config it's worked on my pc and my test pc i think something happen on your modules open an cmd "cd+ path" and type pip uninstall -r requirements.txt then click on "install.bat"

**Comment by nokapzxackx** [comment]
worked.

**Comment by KSCHdsc** [comment]
good
