### ISSUE TITLE
ksch j'attends toujours mes 10 balles

### ISSUE THREAD

**Issue by Bubblegumdu37** [KSCHdsc/BlackCap-Grabber#110]
J'ai vu que tu ne me répondais plus sur discord, je sais pas si tu m'ignores exprès ou que tu ne peux pas répondre, mais je pense porter plainte contre toi et tes potes si tu ne les redonnes pas.

**Comment by KSCHdsc** [comment]
Tu empiètes sur mon lieux de travail et tu me menaces ? Je ne t’ai rien pris personnellement porte plainte si ça te chante je n’ai rien fais d’illégal. Je ne réponds pas car je ne suis tous simplement pas connecté la menace ne marche pas avec moi

**Comment by Bubblegumdu37** [comment]
bah c'est juste que tu pirates mon comptes, tu le passes à tes potes qui s'amusent à détruire mon pc, ma cc et me vole de l'argent. Tu vas pas me dire que c'est pas ta faute. tu me dis que tu vas me rendre les 10 balles. le virement peut se faire en moins de 2 minutes, mais tu rechignes toujours à le faire. J'en viens à la menace car on dirait que tu t'en fous, moi non. j'ai perdu quasiment tout mes contacts sur discord, serveurs, etc. Par contre tu oses dire que tu n'as rien fait d'illégal alors que tu donnes mes infos personnelles à tes potes, te connectes à mon compte sans autorisation. Et excuse moi de te parler ici mais c'est le seul moyen que j'ai trouvé pour te contacter.
![image](https://user-images.githubusercontent.com/108238236/221383888-4532d043-def2-4abc-b4dc-beda051950d9.png)

**Comment by KSCHdsc** [comment]
etant donné que les informations collecté ont été acquissent de manière open source et légal et que pour ma part aucun compté de messagerie n'a été touché tu ne peux pas porter plainte de plus le compte sur lequel tu dis que mes amis t'ont piraté a été supprimé la preuve n'est pas tangible pour ma part, je suis clean :)

**Comment by Bubblegumdu37** [comment]
Et moralement t'es clean ? et dire que je pensais vraiment que tu avais une once de morale quand t'as dit que tu allais me rendre mes 10 balles...
