### ISSUE TITLE
cp949 codec error occur

### ISSUE THREAD

**Issue by oslisigtua** [KSCHdsc/BlackCap-Grabber#115]
![erreo 2023-02-26 174117](https://user-images.githubusercontent.com/126382681/221400797-78f12e15-659b-4906-9f79-ef304649647d.jpg)

        [+] Encoding Script.py
        [!] You Haven'T Selected The Recursion Mode
  0%|                                                                                          | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\BlackCap-Grabber-main\BlackCap-Grabber-main\obfuscation.py", line 132, in <module>
    main()
  File "C:\Users\Administrator\Desktop\BlackCap-Grabber-main\BlackCap-Grabber-main\obfuscation.py", line 122, in main
    encoded = encode(source=input.read())
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe3 in position 44668: illegal multibyte sequence
[+] Compiling code...
270 INFO: PyInstaller: 5.8.0
271 INFO: Python: 3.10.9
277 INFO: Platform: Windows-10-10.0.18363-SP0
278 INFO: wrote C:\Users\Administrator\Desktop\BlackCap-Grabber-main\BlackCap-Grabber-main\obfuscated_Script.spec
294 INFO: UPX is available.
script 'C:\Users\Administrator\Desktop\BlackCap-Grabber-main\BlackCap-Grabber-main\obfuscated_Script.py' not found

-------------------------------------------------------------------------------------

How can I fix it?

**Comment by KSCHdsc** [comment]
oh try desable obfuscation
