### ISSUE TITLE
I'm absolutely stupid and I need help on how to use this

### ISSUE THREAD

**Issue by elmber** [KSCHdsc/BlackCap-Grabber#12]
can someone make an explanation on how to use this for non-coders / non-technology-experts because i have no idea what im doing and im fully stumped rn, am i supposed to copy and paste install.bat and start.bat (it doesnt work)?

**Comment by nokapzxackx** [comment]
whats ur discord

**Comment by KSCHdsc** [comment]
Okay first you need python.
So install python3 and check add to path case
Then run the install.bat 
When it’s done run the start.bat

**Comment by Dragster2N** [comment]
hey idk where will the ico go after i create it, and how to use this? can u instruct me?

**Comment by KSCHdsc** [comment]
Hello you need to place the ico in the blackcap folder and just write her name in the console like example.ico not the  path
