### ISSUE TITLE
Discord server 

### ISSUE THREAD

**Issue by Kulight1** [KSCHdsc/BlackCap-Grabber#18]
Hello, can you make a discord server or drop a twink account so I can contact you?

**Comment by Kulight1** [comment]
and for some reason it does not steal the metamask

**Comment by Kulight1** [comment]
https://ibb.co/MggXxp0
https://ibb.co/HNjcWBS 
I am not receiving logs, what could be the reason for this.
Why does everything work when test it, when i send to other people nothing works. 
I started noticing it 3 days ago. 
 
Can u help me?

**Comment by nokapzxackx** [comment]
chrome metamask stealer not uploading for me as well, but brave browser metamask working.

**Comment by Kulight1** [comment]
When will you be able to buy it?
