### ISSUE TITLE
whats this?

### ISSUE THREAD

**Issue by nokapzxackx** [KSCHdsc/BlackCap-Grabber#19]
![image](https://user-images.githubusercontent.com/70822960/201960908-0f3ac5c6-b182-405a-903b-e62638539bc4.png)
This is decoded to be a crypto regex, but why is it here?

**Comment by KSCHdsc** [comment]
I forgot to remove it from the old regex system because it was detected by anti virus but the regex did not work correctly

**Comment by nokapzxackx** [comment]
Looks similar to a crypto regex.

**Comment by nokapzxackx** [comment]
![image](https://user-images.githubusercontent.com/70822960/201962054-789c85f4-27cc-4c72-a5f3-767b3e6170bc.png)

**Comment by KSCHdsc** [comment]
Yeah but it’s the old Discord token regex who begin with NT

**Comment by nokapzxackx** [comment]
Oh okay.
