### ISSUE TITLE
malware (probably not)

### ISSUE THREAD

**Issue by pancak3boy** [KSCHdsc/BlackCap-Grabber#36]
my friend ran my stub to test it and he got joined into random servers + got nuked

**Comment by KSCHdsc** [comment]
Bruh if you friend are been grabbed it’s not my fault

**Comment by pancak3boy** [comment]
HE RAN MY STUB. MY STUB and he got hacked. I didnt hack him so who did?

**Comment by KSCHdsc** [comment]
Hm he probably download another script my script his totally open source

**Comment by pancak3boy** [comment]
hmm true mb for accusing just wanted to see if u would delete to make sure XD

**Comment by KSCHdsc** [comment]
Yeah no problem 😉
