### ISSUE TITLE
the exe disappears the second i make it  

### ISSUE THREAD

**Issue by jammi22** [KSCHdsc/BlackCap-Grabber#37]
when i make the exe file it disappears instantly and i did everything correct. and i have my antivirus turned off

**Comment by KSCHdsc** [comment]
Hm can you add me on Discord ?

**Comment by KSCHdsc** [comment]
You’re the 2ond one who said that

**Comment by jammi22** [comment]
> You’re the 2ond one who said that
what is ur discord

**Comment by KSCHdsc** [comment]
KSCH reposty#0777

**Comment by jammi22** [comment]
> KSCH reposty#0777

added

**Comment by KSCHdsc** [comment]
patched
