### ISSUE TITLE
crazy good skid tbf

### ISSUE THREAD

**Issue by Smug246** [KSCHdsc/BlackCap-Grabber#40]
https://github.com/Smug246/Luna-Token-Grabber

**Comment by KSCHdsc** [comment]
I didn't take anything from YOUR script put in by the builder, that I had to modify since our grabbers have nothing in common.
BUT i put your credit here :)

https://github.com/KSCHdsc/BlackCap-Grabber#%EF%B8%8F%EF%B8%8F-〢-forked-from

**Comment by KSCHdsc** [comment]
You've a good script but blackcap is best but i like your stuff :(

**Comment by Smug246** [comment]
um u literally copy n pasted my obfuscation script and it looks like u just mixed wasp and hazard. and your readme is just completely skidded off hazard. Wondering if you can code tbh

**Comment by Smug246** [comment]
and u did completley take my builder as well i've just noticed u added ur logo but the actual script is the same. and you don't have 0 detections lmao

**Comment by KSCHdsc** [comment]
hm i take your obfuscation too but she is detected so...

**Comment by KSCHdsc** [comment]
i got 0 detection i can prove it right now

**Comment by Smug246** [comment]
sure u do. ye go on. compile the file to .exe and scan it lol

**Comment by KSCHdsc** [comment]
and hazard is completly un-usable i just take a part of some grabber script and i add more features like an injection :)

**Comment by KSCHdsc** [comment]
pyinstaller is detected okay but when you build it with "cxfreeze" or other you got 0 detect

**Comment by KSCHdsc** [comment]
Cython or bbfreeze

**Comment by KSCHdsc** [comment]
i just don't put my own builder here

**Comment by Smug246** [comment]
lmao ye no shit with cxfreeze. but then you have to send a folder lmao

**Comment by KSCHdsc** [comment]
yeah unless you mind

**Comment by KSCHdsc** [comment]
bind*

**Comment by Smug246** [comment]
hazard isnt unusable either. it was the first logger to have an injection as rdimo the owner made the injection

**Comment by KSCHdsc** [comment]
nop it was anarchy stealer and piratestealer

**Comment by KSCHdsc** [comment]
rdimo put a credit for the injection of piratestealer

**Comment by KSCHdsc** [comment]
he was inspired by his script

**Comment by KSCHdsc** [comment]
but i created my own injection for blackcap no one got the same

**Comment by Smug246** [comment]
oh ye true. but still. pirate had a shitty injection that barely worked. rdimo made his and it blew up straight away

**Comment by KSCHdsc** [comment]
yeah you're right

**Comment by KSCHdsc** [comment]
piratestealer injection was 💩

**Comment by KSCHdsc** [comment]
mine isn't perfect either but I'm working on a simpler and more compact way

**Comment by KSCHdsc** [comment]
but my main goal was not to make stars on github

**Comment by KSCHdsc** [comment]
I just wanted to share with my friends the best grabber I could create so ...

**Comment by KSCHdsc** [comment]
so excuse me if you have the impression that I stole your code it does not have the goal that I was looking for
it's why i but your credit

**Comment by KSCHdsc** [comment]
okay

**Comment by Kyxnite** [comment]
> hazard isnt unusable either. it was the first logger to have an injection as rdimo the owner made the injection

pirate stealer and lunar builder moment 😹

**Comment by furax124** [comment]
> lmao ye no shit with cxfreeze. but then you have to send a folder lmao

can you told me how to do in single exe fud ? or how to blind please
