### ISSUE TITLE
cant find the exe

### ISSUE THREAD

**Issue by GodLike00** [KSCHdsc/BlackCap-Grabber#50]
cannot find the exe.... after doing everything cannot find an exe but there is a file .spec
![image_2023-01-27_074137152](https://user-images.githubusercontent.com/69570105/214995571-04adf7dc-f156-47f2-9533-f3b7ee331a09.png)

**Comment by JohnBusy** [comment]
same

**Comment by KSCHdsc** [comment]
Can you screen final message in console

**Comment by KSCHdsc** [comment]
When you build

**Comment by JohnBusy** [comment]
![err](https://user-images.githubusercontent.com/83535686/215158751-a1bdd1c8-5cce-429f-ae0e-8cb7c555734d.PNG)

**Comment by GodLike00** [comment]
nvm just @JohnBusy just put "n" in "compile the file to a .exe" and then it would make a python file which you can covert into a .exe file by py --> exe

**Comment by JohnBusy** [comment]
> nvm just @JohnBusy just put "n" in "compile the file to a .exe" and then it would make a python file which you can covert into a .exe file by py --> exe
doesn't work. just can't find file

**Comment by JohnBusy** [comment]
it worked i just put yes instead of y lol

**Comment by KSCHdsc** [comment]
pat
