### ISSUE TITLE
it is does'nt send me nothing to my discord server

### ISSUE THREAD

**Issue by edeiber441** [KSCHdsc/BlackCap-Grabber#51]
i try to execute the .exe and yes it open a cmd and fastly close but happens nothing after that

**Comment by DtKdPython** [comment]
same but it only works for not others

**Comment by KSCHdsc** [comment]
Hm your victim need to use Windows 10/11 only

**Comment by edeiber441** [comment]
i have windows 11 and when i try toe execute it in my pc doesn't send nothing to discord

**Comment by edeiber441** [comment]
i use the last version of phyton or 3.10.0

**Comment by KSCHdsc** [comment]
Can you try to launch with .py code in terminal? To see error

**Comment by edeiber441** [comment]
ok

**Comment by edeiber441** [comment]
give me a minute

**Comment by edeiber441** [comment]
![image](https://user-images.githubusercontent.com/123851245/215347701-4d7ae08b-ba88-48c6-b846-c9b02c35c4fb.png)

**Comment by edeiber441** [comment]
pyperclip it is not on the requirements list

**Comment by KSCHdsc** [comment]
Fuck my bad

**Comment by edeiber441** [comment]
add it i already installed pyper

**Comment by edeiber441** [comment]
ok i try now

**Comment by KSCHdsc** [comment]
Okay

**Comment by edeiber441** [comment]
still doesn't work dont send anything to discord

**Comment by KSCHdsc** [comment]
No error ?

**Comment by edeiber441** [comment]
hmm see this
![image](https://user-images.githubusercontent.com/123851245/215348069-2eec1e36-6093-49b2-b7a1-b4117c2c5712.png)

**Comment by edeiber441** [comment]
no in the requirements

**Comment by KSCHdsc** [comment]
Add KSCH CP0#0777 and Send me your error

**Comment by edeiber441** [comment]
sure

**Comment by edeiber441** [comment]
ok i send the friend request

**Comment by edeiber441** [comment]
bro accept the friend request

**Comment by edeiber441** [comment]
you have dm disabled

**Comment by edeiber441** [comment]
![image](https://user-images.githubusercontent.com/123851245/215352084-f4aa8bb2-9a9c-4920-a1dc-ec21f21a71f4.png)

**Comment by edeiber441** [comment]
WORKING!!! it is upx i change it for another upx i found

**Comment by Drakz-z** [comment]
can you tell how you fixed it

**Comment by KSCHdsc** [comment]
you need to re install upx
