### ISSUE TITLE
when i create a new .exe the and i put the .ico file its accepts but the .exe doesn't have .ico

### ISSUE THREAD

**Issue by edeiber441** [KSCHdsc/BlackCap-Grabber#54]
when i create a new .exe the and i put the .ico file its accepts but the .exe doesn't have .ico

**Comment by edeiber441** [comment]
i dont have any error all works only that

**Comment by edeiber441** [comment]
its work random sometimes work and no work

**Comment by KSCHdsc** [comment]
https://youtu.be/QD1xJjhEypg
you can use resource hacker

**Comment by edeiber441** [comment]
thx i try

**Comment by edeiber441** [comment]
works!
