### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by RealMaMo1086** [KSCHdsc/BlackCap-Grabber#63]
I've tried everything I've also looked at all the tickets when I run it and choose what features I want but when It comes to the building section the file gets deleted, and my antivirus is also off please help me fix/resolve this issue.

**Comment by KSCHdsc** [comment]
can you record

**Comment by RealMaMo1086** [comment]
How do is send it then?

**Comment by RealMaMo1086** [comment]
Can i just sharesreen?
