### ISSUE TITLE
UnicodeDecodeError: 'charmap'

### ISSUE THREAD

**Issue by ilhan77777** [KSCHdsc/BlackCap-Grabber#65]
At the last, it shows error and does not create any files.
I added a screenshot.
python 3.11
![Adsız](https://user-images.githubusercontent.com/115109751/216786029-a2a1f3c1-db2e-4f70-843f-01af9a292907.jpg)

**Comment by Smug246** [comment]
bros a skid so probs doesnt know how to fix this

**Comment by KSCHdsc** [comment]
Lmao issu already fixed with the new update
Luna grabber: 140 stars
Blackcap: 160 stars
You’ve skid vespy and « powershell grabber » for you new « GUI »
🫵💩

**Comment by KSCHdsc** [comment]
You’re a skid and your grabber was detect by all famous AV

**Comment by KSCHdsc** [comment]
Don’t be mad

**Comment by KSCHdsc** [comment]
Your injection is a skid From Hazard and your script too

**Comment by Smug246** [comment]
lmao bro u skidded everyone. not one part of the code is yours. stars dont mean anything. wheres your proof of any of this

**Comment by Smug246** [comment]
show me the similarities in my script to hazard. show me where i stole the builder💀

**Comment by Smug246** [comment]
make something from scratch urself then talk to me. do you even know how to fix the charmap error. go on tell me

**Comment by KSCHdsc** [comment]
don't be a assh0le you are such a fan of blackcap that you come to check the issues

**Comment by KSCHdsc** [comment]
ok so where i took the "crypto address reaplcer"???
and where i take the injection?
OH where i take the obfuscation?

**Comment by KSCHdsc** [comment]
okay okay i take your builder but all I modified the entirety of your old shitty builder which is not even yours

**Comment by KSCHdsc** [comment]
blackcap has been published in oct 2022 and luna may 2022
6 month of differences
and i still get new stars every days

**Comment by Smug246** [comment]
injection is a mix of hazard and pirate. crypto replacer i got no clue but ur too much of a skid too have made it. and obfuscation is a piece of piss to deobf. idk why u keep saying the builder isnt mine. show me where i took it from then. how you get stars is beyond me as ur stealer is so shit and its not fud at all. i check the issues to see how clueless you are because you dont know how to fix anything. probs ask chat gpt or something

**Comment by ilhan77777** [comment]
> 
I had this problem after the last update. There was no problem in the previous version.

**Comment by KSCHdsc** [comment]
add me on discord please

**Comment by Smug246** [comment]
https://github.com/R4L4N-XD/Py-Fuscate/blob/main/encrypt.py lmao found where u got ur obfuscation from as well lmaoooooo

**Comment by Smug246** [comment]
> add me on discord please

who u talking to

**Comment by KSCHdsc** [comment]
no u

**Comment by KSCHdsc** [comment]
you can too but idk why i would speak with you

**Comment by KSCHdsc** [comment]
KSCH CP0#0777

**Comment by Smug246** [comment]
> https://github.com/R4L4N-XD/Py-Fuscate/blob/main/encrypt.py lmao found where u got ur obfuscation from as well lmaoooooo

u gonna reply to this or not and admit your a skid. then ill leave

**Comment by KSCHdsc** [comment]
look in the pyfuscate issue he add me on discord and we speak about it

**Comment by KSCHdsc** [comment]
he authorized me to use it I wanted to see if you found where it came from

**Comment by KSCHdsc** [comment]
just trolling

**Comment by KSCHdsc** [comment]
add me on discord

**Comment by Smug246** [comment]
i did

**Comment by Smug246** [comment]
![image](https://user-images.githubusercontent.com/99215486/216838454-26e25293-666b-4fc4-b0ab-1298c499394d.png)
u said u didnt take it tho. u did

**Comment by Smug246** [comment]
smug#6945

**Comment by KSCHdsc** [comment]
no i say "where i take"

**Comment by Smug246** [comment]
ye implying that you didnt take it from anywhere when you did

**Comment by Smug246** [comment]
just admit ur a skid and ill leave.

**Comment by KSCHdsc** [comment]
you can add me on discord

**Comment by Smug246** [comment]
i did lol
