### ISSUE TITLE
Pastebin error

### ISSUE THREAD

**Issue by A1daTR** [KSCHdsc/BlackCap-Grabber#66]
requests.exceptions.SSLError: HTTPSConnectionPool(host='pastebin.com', port=443): Max retries exceeded with url: /raw/(link) (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:992)')))

**Comment by KSCHdsc** [comment]
Did you touch at the pastebin inside ? He is used for regex detection bypass

**Comment by A1daTR** [comment]
No, I didn't touch the code.

**Comment by A1daTR** [comment]
I just changed the link here (not in code) incase it has some private details.

**Comment by A1daTR** [comment]
What is the solution?
