### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by MySkHigh** [KSCHdsc/BlackCap-Grabber#7]
![image](https://user-images.githubusercontent.com/117020519/199057277-e952d8b2-0239-4d6b-92fa-8d86478b1250.png)
i installed requirments and i got tthis when running start.bat what does it mean?

**Comment by KSCHdsc** [comment]
Sorry my fault type pip install alive_progress

**Comment by MySkHigh** [comment]
> Sorry my fault type pip install alive_progress

![image](https://user-images.githubusercontent.com/117020519/199058800-a0047066-6559-4d77-b692-5d62f5c9e5d7.png)
![image](https://user-images.githubusercontent.com/117020519/199058957-78342bd7-8d38-4e31-ac46-e10600541f62.png)
hmhh :/ still having issue

**Comment by MySkHigh** [comment]
> pip install alive-progress

still ssame even i installed aliveprogress i try restart my pc

**Comment by supergarixd** [comment]
Make shure you are using "pip install alive-progress" instead of "pip install alive_progress"
