### ISSUE TITLE
how to fix ERROR

### ISSUE THREAD

**Issue by maxhunter1990** [KSCHdsc/BlackCap-Grabber#72]
![Capture](https://user-images.githubusercontent.com/123949863/217572519-4c368ed8-1b9d-4ffa-a956-5b50e86dea5f.PNG)

**Comment by KSCHdsc** [comment]
working on

**Comment by KSCHdsc** [comment]
Try to re install pypiwin32

**Comment by KSCHdsc** [comment]
Ok i think that’s a connection problem can you retry with another connection
