### ISSUE TITLE
Sending.

### ISSUE THREAD

**Issue by secunda0** [KSCHdsc/BlackCap-Grabber#74]
I configured mine as .py because im having an issue with the .exe it displays some error. Besides from that when I run my .py runs flawlessly but when I sent the file to my burner through discord and ran it it wouldn't work? Is there something I did wrong or do I have to send it a different way?

**Comment by KSCHdsc** [comment]
an error is displayed?

**Comment by KSCHdsc** [comment]
You can use mediafire and mega but if you have an error with Discord it won't change with mediafire

**Comment by secunda0** [comment]
> an error is displayed?

Yes when using the .exe setting when configurating a file it will send this error I think someone posted it in one of the issues can't remember if it was opened or closed. But thank you for lettting me know how to send it properly.

**Comment by secunda0** [comment]
> You can use mediafire and mega but if you have an error with Discord it won't change with mediafire

I just made a mediafire download when I went to download it on my burner it wouldn't pull any information but when I downloaded it on my machine and ran it there was no problem.

**Comment by KSCHdsc** [comment]
patched
