### ISSUE TITLE
Anti Virtual-Machine issue

### ISSUE THREAD

**Issue by DraxFM** [KSCHdsc/BlackCap-Grabber#75]
So basically when I configure my grabber and enable the option to kill VirusTotal Machine/Virtual Machines the script breaks. I can run it and it doesn't even pop an error, but the data isn't sent to my webhook. I tried it several times and it didn't work even once so far. When I select the exact same options just without the Anti-VM option, everything works fine.

In addition I also checked the task manager and yes, the file shows two processes in which one is taking up some RAM meaing it is actually searching my PC for various information but something avoids it from sending this to my webhook. I am kind of familiar with python and other languages. I would have used the "discord_webhook" pip because I created some scripts and the ones using the library form discord_webhook were running more fluently.

If someone could tell me what exactly is causing that to happen, it would be appreciated.
Thanks in advance!

**Comment by KSCHdsc** [comment]
try to create your grabber without activating the "hide console", "compil in .exe" options and try to launch it via visual studio code to check for errors

**Comment by XTremeDev101** [comment]
> try to create your grabber without activating the "hide console", "compil in .exe" options and try to launch it via visual studio code to check for errors

I did what you told me and Visual Studio is not making me aware of any errors as seen in the bottom left corner of the Image I linked to this reply. 0 Warnings and 0 Errors. ![Screenshot (7)](https://user-images.githubusercontent.com/79086740/218287421-5a31bf6e-1c44-472a-af02-8a3171c062f3.png)
