### ISSUE TITLE
need help installing i do not know waht is needed

### ISSUE THREAD

**Issue by TornadoStormTV** [KSCHdsc/BlackCap-Grabber#80]
![image](https://user-images.githubusercontent.com/125149145/218273236-eb729516-c0b7-42a5-b63e-efa3ab42346a.png)

**Comment by KSCHdsc** [comment]
Hey sorry it's a temporary error because of the api "api.myip.com" when their api will be put back in order the grabber will work again

**Comment by KSCHdsc** [comment]
patched !

**Comment by TornadoStormTV** [comment]
so python is down as we speak

**Comment by KSCHdsc** [comment]
nop only the api i patched it by changing the api
