### ISSUE TITLE
Detected by Antivirus 

### ISSUE THREAD

**Issue by maxhunter1990** [KSCHdsc/BlackCap-Grabber#82]
File exe Detected By antivirus, how obfuscate?

**Comment by KSCHdsc** [comment]
i sell premium builder

**Comment by maxhunter1990** [comment]
oh how to buy it?
and how much?

**Comment by KSCHdsc** [comment]
15 for lifetime

**Comment by maxhunter1990** [comment]
15$?

**Comment by KSCHdsc** [comment]
yep

**Comment by maxhunter1990** [comment]
how to contact you?telegram or discord

**Comment by mario3993** [comment]
same, i want to buy it but couldn't contact you

**Comment by maxhunter1990** [comment]
how to buy it?

**Comment by KSCHdsc** [comment]
KSCH CP0#0777

**Comment by maxhunter1990** [comment]
he is a scammer.

**Comment by maxhunter1990** [comment]
![tempsnip](https://user-images.githubusercontent.com/123949863/220889804-13594709-fbb8-4282-8aed-98e40a53c340.png)
![Uploading rr.PNG…]()

**Comment by maxhunter1990** [comment]
just create by cx-freez
