### ISSUE TITLE
dont create build file

### ISSUE THREAD

**Issue by huhdeveloper** [KSCHdsc/BlackCap-Grabber#85]
https://prnt.sc/DAfNVuh0PUZ7

**Comment by KSCHdsc** [comment]
don't enable "obfuscation"

**Comment by KSCHdsc** [comment]
there is some problem with char ・

**Comment by huhdeveloper** [comment]
https://www.virustotal.com/gui/file/bb531321ace82f82d28af6200db733c8557d57e4b70f7ed4091fd44e80f0f215?nocache=1
16 detection ?
