### ISSUE TITLE
Envoie sur webhook

### ISSUE THREAD

**Issue by furax124** [KSCHdsc/BlackCap-Grabber#90]
Je reçois rien sur mon webhook aucun message d’erreur juste rien qui s’envoie

**Comment by MrRobot213** [comment]
Pareil

**Comment by MrRobot213** [comment]
Tu as trouve la solution ou un nouveau grabber ?
J'en recherche un aussi puissant que celui la

**Comment by KSCHdsc** [comment]
quel est le message d'erreur?

**Comment by MrRobot213** [comment]
J en ai pas le webhook marche que contre moi
Les donnes de mes victimes n'apparaissent pas du tout alors que ils ont installé le fichier et ouvert
Je capte pas .

**Comment by MrRobot213** [comment]
y a pas de messages d erreur

**Comment by MrRobot213** [comment]
@KSCHdsc un conseil ou une idee ?

**Comment by furax124** [comment]
> Tu as trouve la solution ou un nouveau grabber ?
> J'en recherche un aussi puissant que celui la

Non dsl j’en ai pas un mlr enfin pas un aussi bon que black cap

**Comment by KSCHdsc** [comment]
essaie de te build un blackcap sans le compil en .exe et sans l'obfu active pas non plus "hide console" et "anti debug"

**Comment by KSCHdsc** [comment]
juste pour test

**Comment by furax124** [comment]
> essaie de te build un blackcap sans le compil en .exe et sans l'obfu active pas non plus "hide console" et "anti debug"

wshhh je vais faire sa mais en bon obfusc et en exe et hide déjà fait mais le debug je dois mettre quoi (

**Comment by furax124** [comment]
> essaie de te build un blackcap sans le compil en .exe et sans l'obfu active pas non plus "hide console" et "anti debug"

Marche toujours pas

**Comment by furax124** [comment]
> essaie de te build un blackcap sans le compil en .exe et sans l'obfu active pas non plus "hide console" et "anti debug"

Oe sa marche mais après sa marche plus ?

**Comment by KSCHdsc** [comment]
ça marche sans erreur?

**Comment by furax124** [comment]
> ça marche sans erreur?

Oui

**Comment by furax124** [comment]
> ça marche sans erreur?

Exception in thread Thread-20 (getCookie): ces rap Exception in thread Thread-24 (getCookie):

**Comment by MrRobot213** [comment]
Donc y a une erreur ?

**Comment by MrRobot213** [comment]
Tu recois les données

**Comment by furax124** [comment]
> Tu recois les données

Oe

**Comment by furax124** [comment]
> Tu recois les données

oui mais juste avec ses options la pas avec les truc ect en exe et tout
