### ISSUE TITLE
Victim's data don't come although they click it .

### ISSUE THREAD

**Issue by MrRobot213** [KSCHdsc/BlackCap-Grabber#91]
IDK why but when the file is created and my victim clicks it in front of me data dont come but when I click myself all my data are here @KSCHdsc can u help me to figure out what4s the problem my webhook works only against me 
Please answer.

**Comment by KSCHdsc** [comment]
hmh if you enable antidebug the program wont run if victime don't have 3go ram and 200+ go storage

**Comment by KSCHdsc** [comment]
probably this? or do he use a modified windows10/11?

**Comment by PeakScripts** [comment]
> hmh if you enable antidebug the program wont run if victime don't have 3go ram and 200+ go storage

so i need to disable the antidebug for it to work?

**Comment by KSCHdsc** [comment]
yes
