### ISSUE TITLE
what is mdp.txt

### ISSUE THREAD

**Issue by chiron853** [KSCHdsc/BlackCap-Grabber#92]
in interesting files found tab there is a mdp.txt and it contains some random keys but what is it used for

**Comment by KSCHdsc** [comment]
that's a "files" sniper bro the grabber snipe auto

**Comment by chiron853** [comment]
> that's a "files" sniper bro the grabber snipe auto

but there is a key in mdp.txt and how do you use it

**Comment by KSCHdsc** [comment]
idk that's your victim "mdp" probably for a game or for application
