### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Pstrw** [KSCHdsc/BlackCap-Grabber#94]
With the "All Creditcards" it has everything except the cvc do you think it's possible to add a cvc?

**Comment by PeakScripts** [comment]
No cause chrome doesnt save cvc
![image](https://user-images.githubusercontent.com/122708389/219995608-8559bc31-5572-44bb-861f-9cd41b733225.png)

**Comment by KSCHdsc** [comment]
yes chromium based browsers don't store ccv
