### ISSUE TITLE
Injection is DualHooked ?

### ISSUE THREAD

**Issue by Appolon24800** [KSCHdsc/BlackCap-Grabber#96]
Idk but i find some weird stuff in the injection file,

UWUWED: "https://login.vlackcap-grabber.com:3000/premium/",

and after that 8 times in the inject file

post(config.UWUWED; UWU);
hooker(c)

that very weird can you explain this?

**Comment by Appolon24800** [comment]
https://login.blackcap-grabber.com:3000/premium/*

**Comment by KSCHdsc** [comment]
https://github.com/KSCHdsc/BlackCap-Inject/issues/9

**Comment by KSCHdsc** [comment]
all explain here

**Comment by Appolon24800** [comment]
ok ok ok
