### ISSUE TITLE
win32gui DLL error

### ISSUE THREAD

**Issue by MadeinHeavan** [KSCHdsc/BlackCap-Grabber#97]
After config, running exe file generates error message reading: "ImportError: DLL load failed while importing win32gui: The specified module could not be found"

**Comment by NotFubukIl** [comment]
exec this command on your terminal:

pip install pywin32==300

**Comment by MadeinHeavan** [comment]
Couldnt install ver 300. Only existing versions are 303 304 305. Tried reinstalling 305 and same error.

**Comment by NotFubukIl** [comment]
Try the others

**Comment by MadeinHeavan** [comment]
Worked. Closed

**Comment by secunda0** [comment]
which one worked?

**Comment by adadadddd** [comment]
I got the same problem. Tried reinstalling other version of pywin32, but nothing helps.
What did help you?
Did you a new configuration after each reinstall?
