### ISSUE TITLE
Scammer

### ISSUE THREAD

**Issue by maxhunter1990** [KSCHdsc/BlackCap-Grabber#99]
He is Scammer

**Comment by maxhunter1990** [comment]
[maxhunter1990](https://github.com/maxhunter1990) commented [last week](https://github.com/KSCHdsc/BlackCap-Grabber/issues/82#issue-1581274212)
File exe Detected By antivirus, how obfuscate?

@KSCHdsc
Owner
[KSCHdsc](https://github.com/KSCHdsc) commented [last week](https://github.com/KSCHdsc/BlackCap-Grabber/issues/82#issuecomment-1427180878)
i sell premium builder

@maxhunter1990
Author
[maxhunter1990](https://github.com/maxhunter1990) commented [last week](https://github.com/KSCHdsc/BlackCap-Grabber/issues/82#issuecomment-1427432907)
oh how to buy it?
and how much?

@KSCHdsc
Owner
[KSCHdsc](https://github.com/KSCHdsc) commented [last week](https://github.com/KSCHdsc/BlackCap-Grabber/issues/82#issuecomment-1427832774)
15 for lifetime

@maxhunter1990
Author
[maxhunter1990](https://github.com/maxhunter1990) commented [last week](https://github.com/KSCHdsc/BlackCap-Grabber/issues/82#issuecomment-1427981251)
15$?

@KSCHdsc
Owner
[KSCHdsc](https://github.com/KSCHdsc) commented [last week](https://github.com/KSCHdsc/BlackCap-Grabber/issues/82#issuecomment-1428086562)
yep

@maxhunter1990
Author
[maxhunter1990](https://github.com/maxhunter1990) commented [last week](https://github.com/KSCHdsc/BlackCap-Grabber/issues/82#issuecomment-1428089020)
how to contact you?telegram or discord

@[mario3993](https://github.com/mario3993)
mario3993 commented [last week](https://github.com/KSCHdsc/BlackCap-Grabber/issues/82#issuecomment-1428266952)
same, i want to buy it but couldn't contact you

@KSCHdsc
Owner
[KSCHdsc](https://github.com/KSCHdsc) commented [last week](https://github.com/KSCHdsc/BlackCap-Grabber/issues/82#issuecomment-1432346822)
KSCH CP0#0777

**Comment by maxhunter1990** [comment]
![tempsnip](https://user-images.githubusercontent.com/123949863/220547171-723a9ede-9ccb-4fcb-a767-50cbabcae7a2.png)

**Comment by maxhunter1990** [comment]
![rr](https://user-images.githubusercontent.com/123949863/220547289-13cb4ab2-666c-4708-8e1f-5870f01190a1.PNG)

**Comment by PeakScripts** [comment]
can u give me that buildzone.rar :))))))))))))))))))))))))))))))))) my discord is DtKd#0001 <3

**Comment by chiron853** [comment]
> ![rr](https://user-images.githubusercontent.com/123949863/220547289-13cb4ab2-666c-4708-8e1f-5870f01190a1.PNG)

i can tell how to build this fud if you give me that file in return and you dont need any obfuscators because thats how you get detections [DATA-EXPUNGED]#1272
